# Generated by Django 6.0 on 2025-12-31 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the blog post', max_length=200)),
                ('content', models.TextField(help_text='The main content of the blog post')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the post was last updated')),
                ('is_published', models.BooleanField(default=False, help_text='Whether the post is published')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times the post was viewed')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the commenter', max_length=100)),
                ('email', models.EmailField(help_text='Email of the commenter', max_length=254)),
                ('text', models.TextField(help_text='The comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the comment was posted')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the comment is approved')),
                ('post', models.ForeignKey(help_text='The blog post this comment is on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainapp.blogpost')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
